import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import logger from '../logger';
import pg from 'pg';
import { config } from 'dotenv';
import { readFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

// Load environment variables
config();

/**
 * Database migration using Drizzle ORM
 * Uses the migration files generated by drizzle-kit
 */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const schemaSyncModes = {
  auto: 'auto',
  migrate: 'migrate',
  push: 'push',
} as const;

export type SchemaSyncMode = (typeof schemaSyncModes)[keyof typeof schemaSyncModes];

interface RunDrizzleMigrationsOptions {
  mode?: SchemaSyncMode;
}

const isValidSchemaSyncMode = (value: string | undefined): value is SchemaSyncMode => {
  return value === schemaSyncModes.auto
    || value === schemaSyncModes.migrate
    || value === schemaSyncModes.push;
};

export async function runDrizzleMigrations(
  options: RunDrizzleMigrationsOptions = {},
): Promise<void> {
  const mode = options.mode ?? schemaSyncModes.auto;

  try {
    logger.info('Starting database schema setup...');

    // First ensure the database exists
    await ensureDatabaseExists();

    await synchronizeDatabaseSchema(mode);
    await applyRowLevelSecurityPolicies();

  } catch (error: any) {
    logger.error(`Database setup failed: ${error.message}`);
    throw error;
  }
}

export function parseSchemaSyncMode(value: string | undefined): SchemaSyncMode {
  if (!isValidSchemaSyncMode(value)) {
    throw new Error(`Invalid migration mode: ${value ?? 'undefined'}. Expected one of: auto, migrate, push.`);
  }

  return value;
}

/**
 * Test database connection
 */
export async function testDatabaseConnection(): Promise<boolean> {
  try {
    const testClient = postgres(process.env.DATABASE_URL!, {
      max: 1,
      ssl: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? {
        rejectUnauthorized: false
      } : false
    });

    await testClient`SELECT 1`;
    await testClient.end();
    return true;
  } catch (error) {
    logger.error('Database connection test failed:', error);
    return false;
  }
}

/**
 * Ensure the database exists, create it if it doesn't
 */
async function ensureDatabaseExists(): Promise<void> {
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL environment variable is required');
  }

  const url = new URL(process.env.DATABASE_URL);
  const dbName = url.pathname.slice(1); // Remove leading slash

  if (!dbName) {
    throw new Error('Database name not found in DATABASE_URL');
  }

  // Create connection to postgres database to check if target database exists
  const postgresUrl = new URL(process.env.DATABASE_URL);
  postgresUrl.pathname = '/postgres';

  const postgresPool = new pg.Pool({
    connectionString: postgresUrl.toString(),
    ssl: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? {
      rejectUnauthorized: false
    } : false
  });

  try {
    // Check if database exists
    const result = await postgresPool.query(
      'SELECT 1 FROM pg_database WHERE datname = $1',
      [dbName]
    );

    if (result.rows.length === 0) {
      logger.info(`Database "${dbName}" does not exist. Creating it...`);

      // Create the database
      await postgresPool.query(`CREATE DATABASE "${dbName}"`);
      logger.info(`Database "${dbName}" created successfully`);
    } else {
      logger.info(`Database "${dbName}" already exists`);
    }
  } catch (error: any) {
    logger.error(`Error ensuring database exists: ${error.message}`);
    throw error;
  } finally {
    await postgresPool.end();
  }
}

async function synchronizeDatabaseSchema(mode: SchemaSyncMode): Promise<void> {
  if (mode === schemaSyncModes.migrate) {
    await applyMigrationFiles();
    return;
  }

  if (mode === schemaSyncModes.push) {
    await pushSchema();
    return;
  }

  try {
    await pushSchema();
  } catch (pushError: any) {
    logger.warn(`Schema push failed, trying migration files instead: ${pushError.message}`);

    try {
      await applyMigrationFiles();
    } catch (migrationError: any) {
      logger.warn('Migration also failed, verifying database connection...');
      await testDatabaseConnection();
      logger.info('Database connection verified - schema may already exist');
    }
  }
}

async function pushSchema(): Promise<void> {
  const { execFileSync } = await import('child_process');

  logger.info('Synchronizing database schema with drizzle-kit push...');
  const result = execFileSync(
    process.platform === 'win32' ? 'npx.cmd' : 'npx',
    ['drizzle-kit', 'push', '--force', '--config=./drizzle.config.ts'],
    {
      stdio: 'pipe',
      encoding: 'utf8',
      cwd: process.cwd(),
    },
  );

  logger.info('Database schema synchronized successfully');
  if (result.includes('No changes detected')) {
    logger.info('Database schema is already up to date');
  }
}

async function applyMigrationFiles(): Promise<void> {
  const migrationClient = postgres(process.env.DATABASE_URL!, {
    max: 1,
    ssl: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? {
      rejectUnauthorized: false,
    } : false,
  });

  try {
    logger.info('Applying migration files...');
    const db = drizzle(migrationClient);
    await migrate(db, { migrationsFolder: './db/migrations' });
    logger.info('Migration files applied successfully');
  } finally {
    await migrationClient.end();
  }
}

async function applyRowLevelSecurityPolicies(): Promise<void> {
  const sqlFilePath = path.resolve(__dirname, 'rls.sql');
  const sql = await readFile(sqlFilePath, 'utf8');

  const policyPool = new pg.Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? {
      rejectUnauthorized: false,
    } : false,
  });

  try {
    logger.info(`Applying row-level security policies from ${sqlFilePath}...`);
    await policyPool.query(sql);
    logger.info('Row-level security policies applied successfully');
  } finally {
    await policyPool.end();
  }
}

