import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import logger from '../logger';
import pg from 'pg';
import { config } from 'dotenv';

// Load environment variables
config();

/**
 * Database migration using Drizzle ORM
 * Uses the migration files generated by drizzle-kit
 */

export async function runDrizzleMigrations(): Promise<void> {
  try {
    logger.info('Starting database schema setup...');

    // First ensure the database exists
    await ensureDatabaseExists();

    // Use drizzle-kit push for idempotent schema management
    // This automatically handles existing schemas and only applies necessary changes
    const { execSync } = await import('child_process');
    
    logger.info('Synchronizing database schema...');
    try {
      // drizzle-kit push is idempotent and safe - it compares current schema with desired schema
      const result = execSync('npm run db:push --workspace=apps/server', { 
        stdio: 'pipe',
        encoding: 'utf8',
        cwd: process.cwd() 
      });
      
      logger.info('Database schema synchronized successfully');
      if (result.includes('No changes detected')) {
        logger.info('Database schema is already up to date');
      }
      
    } catch (pushError: any) {
      // If push fails, fall back to migration files
      logger.warn('Schema push failed, trying migration files...');
      
      const migrationClient = postgres(process.env.DATABASE_URL!, {
        max: 1,
        ssl: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? {
          rejectUnauthorized: false
        } : false
      });

      try {
        const db = drizzle(migrationClient);
        await migrate(db, { migrationsFolder: './db/migrations' });
        logger.info('Migration files applied successfully');
      } catch (migrationError: any) {
        logger.warn('Migration also failed, verifying database connection...');
        await testDatabaseConnection();
        logger.info('Database connection verified - schema may already exist');
      } finally {
        await migrationClient.end();
      }
    }

  } catch (error: any) {
    logger.error(`Database setup failed: ${error.message}`);
    throw error;
  }
}

/**
 * Test database connection
 */
export async function testDatabaseConnection(): Promise<boolean> {
  try {
    const testClient = postgres(process.env.DATABASE_URL!, {
      max: 1,
      ssl: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? {
        rejectUnauthorized: false
      } : false
    });
    
    await testClient`SELECT 1`;
    await testClient.end();
    return true;
  } catch (error) {
    logger.error('Database connection test failed:', error);
    return false;
  }
}

/**
 * Ensure the database exists, create it if it doesn't
 */
async function ensureDatabaseExists(): Promise<void> {
  if (!process.env.DATABASE_URL) {
    throw new Error('DATABASE_URL environment variable is required');
  }

  const url = new URL(process.env.DATABASE_URL);
  const dbName = url.pathname.slice(1); // Remove leading slash
  
  if (!dbName) {
    throw new Error('Database name not found in DATABASE_URL');
  }

  // Create connection to postgres database to check if target database exists
  const postgresUrl = new URL(process.env.DATABASE_URL);
  postgresUrl.pathname = '/postgres';
  
  const postgresPool = new pg.Pool({
    connectionString: postgresUrl.toString(),
    ssl: (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'staging') ? {
      rejectUnauthorized: false
    } : false
  });

  try {
    // Check if database exists
    const result = await postgresPool.query(
      'SELECT 1 FROM pg_database WHERE datname = $1',
      [dbName]
    );

    if (result.rows.length === 0) {
      logger.info(`Database "${dbName}" does not exist. Creating it...`);
      
      // Create the database
      await postgresPool.query(`CREATE DATABASE "${dbName}"`);
      logger.info(`Database "${dbName}" created successfully`);
    } else {
      logger.info(`Database "${dbName}" already exists`);
    }
  } catch (error: any) {
    logger.error(`Error ensuring database exists: ${error.message}`);
    throw error;
  } finally {
    await postgresPool.end();
  }
}

